# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2

before:
  hooks:
    - sh -c "go env -w GOPROXY=direct"
    - go mod download
builds:
  - id: twitch-darwin
    ldflags: 
      - -s -w -X main.buildVersion={{ .Version }} 
    binary: twitch
    env:
      - CGO_ENABLED=1  
      - CC=o64-clang 
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
  - id: twitch-linux
    ldflags:
      - -s -w -X main.buildVersion={{ .Version }}
    binary: twitch
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
  - id: twitch-linux-arm64
    ldflags:
      - -s -w -X main.buildVersion={{ .Version }}
    binary: twitch
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc-9
      - CXX=aarch64-linux-gnu-g++-9
    goos:
      - linux
    goarch:
      - arm64 
  - id: twitch-windows-x64
    ldflags: 
    - -s -w -X main.buildVersion={{ .Version }} 
    binary: twitch
    main: ./main.go
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
  - id: twitch-windows-i386
    ldflags:
      - -s -w -X main.buildVersion={{ .Version }} 
    binary: twitch
    main: ./main.go
    env:
      - CGO_ENABLED=1
      - CC=i686-w64-mingw32-gcc-posix
      - CXX=i686-w64-mingw32-g++-posix
    goos:
      - windows
    goarch:
      - "386" 
scoops:
  -
    repository:
      owner: twitchdev
      name: scoop-bucket
    homepage: https://github.com/twitchdev/twitch-cli
    description: CLI for Twitch's developer offerings
    license: Apache-2.0
brews:
  -
    repository:
      owner: twitchdev
      name: homebrew-twitch
    directory: Formula
    homepage: https://github.com/twitchdev/twitch-cli
    description: CLI for Twitch's developer offerings
    install: |
      bin.install "twitch"
    test: |
      system "#{bin}/twitch", "version"
    license: Apache-2.0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{- title .Os }}_{{- if eq .Arch "386" }}i386{{- else if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}'
    format_overrides:
    - goos: windows
      format: zip
    wrap_in_directory: "true"
    files:
      - docs/*
      - LICENSE
      - NOTICE
      - THIRD-PARTY
      - README.md
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
